Repository microsoftgraph/msgraph-sdk-dotnet-core, pull requests merged in 2020-04, with the labels that each got.

#108 DeltaResponseHandler with System.Text.Json
  pipelines/previewBuild.yml
  pipelines/productionBuild.yml
  pipelines/validatePR.yml
  src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
  src/Microsoft.Graph.Core/Requests/DeltaResponseHandler.cs
  src/Microsoft.Graph.Core/Requests/Upload/UploadResponseHandler.cs
  src/Microsoft.Graph.Core/Serialization/InterfaceConverter.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Authentication/IntegrateWindowsTokenCredentialTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Content/BatchResponseContentTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Middleware/RetryHandlerTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/ResponseHandlerTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadResponseHandlerTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/Upload/UploadSliceRequestTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Tasks/LargeFileUploadTaskTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/ITestEventDeltaCollectionPage.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestAttendee.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestBodyType.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDateTimeTimeZone.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDrive.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestDriveItem.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEmailAddress.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEvent.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionPage.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaCollectionResponse.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestEventDeltaRequest.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestItemBody.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestNotebook.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestRecipient.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/TestModels/ServiceModels/TestUser.cs
Labels: System.Text.Json, breaking change

#109 Fix for incorrect task cancellation
  src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
  src/Microsoft.Graph.Core/Requests/HttpProvider.cs
  src/Microsoft.Graph.Core/Requests/SimpleHttpProvider.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/SimpleHttpProviderTests.cs
Labels: breaking change

#99 Support native plaform Http handlers for Xamarin.Mac
  src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj
  src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Microsoft.Graph.DotnetCore.Core.Test.csproj
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/GraphClientFactoryTests.cs
  tests/Microsoft.Graph.DotnetCore.Core.Test/Requests/HttpProviderTests.cs
Labels: ToTriage
